local C = require('imperialIllumination.colors')
return {

    DiagnosticError = { fg = C.red.soft },
    DiagnosticWarn = { fg = C.yellow.base },
    DiagnosticInfo = { fg = C.blue.b0 },
    DiagnosticHint = { fg = C.green.bright },
    DiagnosticOk = { fg = C.green.base },
    DiagnosticUnderlineError = { sp = C.red.bright },
    DiagnosticUnderlineWarn = { sp = C.yellow.base },
    DiagnosticUnderlineInfo = { sp = C.blue.base },
    DiagnosticUnderlineHint = { sp = C.cyan.bright },
    DiagnosticUnderlineOk = { sp = C.green.base },
    -- DiagnosticVirtualTextError = {},
    -- DiagnosticVirtualTextWarn = {},
    -- DiagnosticVirtualTextInfo = {},
    -- DiagnosticVirtualTextHint = {},
    -- DiagnosticVirtualTextOk = {},
    -- DiagnosticFloatingError = {},
    -- DiagnosticFloatingWarn = {},
    -- DiagnosticFloatingInfo = {},
    -- DiagnosticFloatingHint = {},
    -- DiagnosticFloatingOk = {},
    -- DiagnosticSignError = {},
    -- DiagnosticSignWarn = {},
    -- DiagnosticSignInfo = {},
    -- DiagnosticSignHint = {},
    -- DiagnosticSignOk = {},

    DiagnosticDeprecated = { 'DiagnosticUnderlineError' },
    DiagnosticUnnecessary = { fg = C.black.dark },
}
